name: MSBuild

on:
  push:
    branches:
    - main
    - release/*
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
    - main
    - release/*
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: driver_shim.sln

jobs:
  build:
    runs-on: windows-latest
    environment: build-and-sign

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    
    - name: Checkout submodules
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init

    - name: Setup DevEnv
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        devenv.com ${{env.SOLUTION_FILE_PATH}} /Build "Release|x64"

    - name: Publish
      uses: actions/upload-artifact@v4
      with:
        name: DriverDemo
        path: |
          bin/distribution/

    - name: Publish Symbols
      uses: actions/upload-artifact@v4
      with:
        name: Symbols
        path: |
          bin/x64/Release/driver_aapvr_shim.pdb
